import sqlite3

DATABASE = 'palavras.db'

def create_db():
    palavras = [
    "sagaz", "amago", "negro", "termo", "exito", "mexer", "nobre", "senso", "afeto",
    "algoz", "etica", "plena", "fazer", "tenue", "assim", "mutua", "vigor", "sobre",
    "aquem", "sutil", "porem", "secao", "poder", "fosse", "sanar", "ideia", "cerne",
    "audaz", "moral", "inato", "desde", "muito", "justo", "quica", "honra", "sonho",
    "torpe", "razao", "amigo", "icone", "etnia", "futil", "egide", "anexo", "tange",
    "dengo", "haver", "lapso", "expor", "entao", "tempo", "seara", "mutuo", "bocal",
    "habil", "casal", "saber", "avido", "pesar", "ardil", "graca", "dizer", "obice",
    "causa", "dever", "sendo", "genro", "coser", "xibiu", "tenaz", "paria", "estar",
    "posse", "brado", "crivo", "ainda", "prole", "comum", "temor", "apice", "corja",
    "animo", "detem", "pauta", "ceder", "assaz", "ansia", "culto", "fugaz", "censo",
    "digno", "mundo", "atroz", "forte", "gleba", "vicio", "vulgo", "cozer", "valha",
    "criar", "mesmo", "saude", "reves", "denso", "nenem", "pudor", "dogma", "jeito",
    "todos", "regra", "louco", "atras", "ordem", "merce", "homem", "feliz", "impor",
    "pedir", "banal", "round", "clava", "limbo", "coisa", "usura", "juizo", "sabio",
    "apraz", "forma", "servo", "prosa", "tenro", "desse", "falar", "pifio", "presa",
    "certo", "ajuda", "posso", "cunho", "ontem", "viril", "vendo", "legal", "devir",
    "heroi", "manso", "falso", "meiga", "valor", "reaca", "facil", "visar", "magoa",
    "ebrio", "serio", "acaso", "puder", "fluir", "guisa", "afago", "plato", "linda",
    "lugar", "impio", "temer", "abrir", "garbo", "afins", "praxe", "obter", "gerar",
    "obvio", "cisma", "matiz", "burro", "bruma", "uniao", "pleno", "crise", "exodo",
    "havia", "fluxo", "venia", "senil", "tedio", "ritmo", "morte", "enfim", "levar",
    "tomar", "olhar", "visao", "alibi", "casta", "brega", "genio", "prumo", "parvo",
    "vital", "bravo", "favor", "reles", "cabal", "pulha", "falta", "ouvir", "vivaz",
    "reter", "parco", "tecer", "calma", "valia", "sabia", "outro", "ameno", "laico",
    "grato", "viver", "tendo", "terra", "possa", "nocao", "carma", "passo", "forca",
    "unico", "achar", "nicho", "ranco", "pobre", "noite", "facam", "prime", "rogar",
    "rever", "fardo", "farsa", "fator", "obito", "ativo", "selar", "coeso", "epico",
    "dubio", "anelo", "citar", "sinto", "papel", "nossa", "leigo", "cisao", "sesta",
    "claro", "sonso", "ciume", "adiar", "cesta", "lider", "haste", "velho", "deter",
    "tende", "gente", "humor", "atuar", "revel", "sulco", "ideal", "vemos", "exato",
    "arduo", "ponto", "ficar", "igual", "amplo", "vazio", "fonte", "marco", "labor",
    "feixe", "lavra", "terno", "debil", "hiato", "remir", "senao", "cauda", "capaz",
    "gesto", "otica", "tanto", "imune", "ambos", "varao", "inata", "jovem", "relva",
    "vacuo", "toada", "tenra", "sonsa", "ciclo", "apoio", "cacar", "coçar", "velar",
    "raiva", "algum", "vimos", "pouco", "serie", "xeque", "chuva", "farao", "horda",
    "leito", "fusao", "advem", "entre", "feito", "sente", "probo", "coesa", "doido",
    "minha", "frase", "carro", "cruel", "anuir", "trama", "torco", "verso", "brisa",
    "impar", "rigor", "botar", "chata", "massa", "blase", "lazer", "prece", "maior",
    "dorso", "pegar", "sorte", "signo", "mocao", "seita", "fauna", "covil", "preso",
    "credo", "furor", "casto", "morar", "livro", "flora", "vetor", "adeus", "docil",
    "peste", "liame", "ambas", "comer", "plano", "faina", "houve", "senda", "ocaso",
    "nunca", "pecha", "arido", "saiba", "setor", "praia", "alias", "manha", "virus",
    "peixe", "ardor", "meses", "agora", "visse", "mudar", "salvo", "beata", "aceso",
    "antro", "vulto", "rezar", "vasto", "breve", "pajem", "parte", "saida", "morro",
    "junto", "banzo", "risco", "campo", "otimo", "reger", "prado", "avaro", "sinal",
    "grupo", "aureo", "birra", "anais", "segue", "andar", "lenda", "antes",
    "motim", "opcao", "acima", "chulo", "estao", "fugir", "aurea", "leite", "nacao",
    "conta", "rapaz", "atomo", "brava", "treta", "vilao", "fruir", "oxala", "parar",
    "verbo", "idolo", "texto", "fitar", "indio", "tirar", "tenso", "jazia", "prazo",
    "reino", "gerir", "puxar", "festa", "alude", "norma", "traga", "tosco", "exame",
    "epoca", "prova", "filho", "atrio", "bando", "malta", "turba", "corpo", "psico",
    "ancia", "arcar", "preto", "sinha", "cheio", "aonde", "acesa", "aviao", "voraz",
    "manha", "fatal", "fatos", "sarca", "quase", "copia", "praga", "venal", "certa",
    "ligar", "quota", "logro", "nosso", "magia", "fixar", "apego", "dessa", "nivel", "oasis", "afora", "coito", "pompa", 
    "sumir", "soldo", "nodoa", "mente", "alado", "messe", "caixa", "tocar", "longe", 
    "jirau", "perda", "bonus", "lidar", "parca", "tinha", "livre", "fraco", "verve", 
    "lindo", "apelo", "sexta", "solto", "vezes", "glosa", "firme", "grave", "virao", 
    "opaco", "porta", "bater", "turva", "faixa", "sabia", "astro", "salve", "exijo", 
    "doido", "trupe", "fenda", "irmao", "navio", "pardo", "grata", "elite", "canon", 
    "abriu", "parva", "supra", "atual", "autor", "alcar", "deixa", "besta", "viria", 
    "pique", "junco", "bicho", "cioso", "ficha", "curso", "etico", "douto", "macio", 
    "reses", "pagao", "abuso", "calda", "bioma", "cousa", "posto", "judeu", "desta", 
    "radio", "locus", "caber", "verba", "menos", "retem", "video", "culpa", "supor", 
    "prive", "chato", "aluno", "zelar", "extra", "molho", "drops", "super", "torso", 
    "calao", "gosto", "vosso", "baixo", "light", "suave", "advir", "agudo", "combo", 
    "vinha", "julia", "igneo", "asilo", "orfao", "ruina", "lapis", "facho", "turma", 
    "sitio", "podio", "traco", "turvo", "peito", "estio", "pisar", "passa", "piada", 
    "acoes", "ereto", "pilar", "chama", "brabo", "louca", "amena", "finda", "mosto", 
    "refem", "avida", "mesma", "meigo", "forem", "rouca", "local", "acola", "museu", 
    "facto", "metie", "pareo", "surja", "autos", "cutis", "poeta", "tento", "rumor", 
    "paira", "optar", "lasso", "medir", "teste", "poema", "geral", "coral", "cocho", 
    "drama", "folga", "aviso", "busca", "clima", "feudo", "urgia", "hobby", "boato", 
    "clean", "idoso", "rubro", "tetra", "cetro", "pacto", "feroz", "ateia", "calmo", 
    "movel", "tacha", "amiga", "monge", "ponha", "crime", "golpe", "licao", "acude", 
    "daqui", "carta", "ebano", "ecoar", "cacho", "plumo", "verde", "monte", "vigia", 
    "riste", "corso", "aroma", "casar", "falha", "saldo", "fazia", "briga", "vetar", 
    "conto", "letal", "manga", "pasmo", "artur", "hoste", "itens", "benca", "tribo", 
    "pedra", "volta", "rival", "escol", "grama", "forum", "penta", "troca", "tarde", 
    "swing", "roupa", "manga", "chefe", "sucia", "venha", "unica", "civil", "sosia", 
    "plebe", "natal", "fruto", "uteis", "plaga", "cover", "lesse", "vento", "sarau", 
    "finjo", "amada", "cargo", "atimo", "macro", "nuvem", "ornar", "pinho", "virar", 
    "axila", "orgao", "berro", "arado", "vazao", "magna", "areia", "stand", "farta", 
    "jogar", "jejum", "tchau", "seixo", "beijo", "fosso", "catre", "tiver", "troca", 
    "giria", "legua", "bruta", "traje", "deste", "nesse", "perto", "inter", "midia", 
    "perco", "varoa", "bruto", "assar", "viram", "tutor", "renda", "guria", 
    "trato", "todas", "gabar", "estro", "amado", "porte", "surto", "pomar", "close", 
    "rural", "feita", "canso", "arfar", "rocha", "nesta", "ambar", "pedro", "bazar", 
    "tenha", "silvo", "nessa", "vadia", "vedar", "santo", "depor", "calor", 
    "fossa", "grota", "odiar", "irado", "pavor", "laudo", "cifra", "vista", "negar", 
    "canto", "aviar", "mamae", "etapa", "densa", "xucro", "bucho", "clero", "logos", 
    "visto", "bolsa", "ferpa", "verao", "minar", "regio", "marca", "cinto", "cerca", 
    "vagar", "cenho", "cheia", "segar", "chula", "molde", "lesao", "inves", "horto", 
    "salmo", "agape", "proto", "ruido", "coroa", "paiol", "urdir", "burra", "morfo", 
    "sotao", "largo", "deram", "letra", "pasma", "velha", "simio", "final", "penso", 
    "danca", "pugna", "folha", "vasta", "troco", "esgar", "ubere", "lesto", "narco", 
    "fundo", "jazer", "sofia", "trago", "ceita", "podar", "ufano", "ardis", "quais", 
    "mocho", "linha", "umido", "frota", "bulir", "apear", "ileso", "piche", "troco", 
    "queda", "polis", "preco", "alamo", "neste", "civel", "peita", "resto", "audio", 
    "manto", "matar", "folia", "redor", "monta", "misto", "cosmo", "seiva", "mover", 
    "barro", "chaga", "labia", "bolso", "banto", "outra", "logia", "retro", "chave", 
    "disso", "justa", "limpo", "olhos", "album", "barao", "falsa", "macho", "campa", 
    "nacar", "lutar", "farol", "veloz", "bedel", "louro", "calvo", "gemer", "punha", 
    "axial", "mimar", "porca", "venho", "arroz", "findo", "vazia", "sabor", "louca", 
    "toque", "calca", "rente", "longo", "salva", "enjoo", "zumbi", "lucro", "coevo", 
    "baixa", "viger", "dados", "nariz", "fazes", "lousa", "firma", "demao", "solta", 
    "subir", "samba", "torna", "farto", "urgir", "canil", "forro", "ousar", "diabo", 
    "sigla", "fugiu", "valer", "reler", "gueto", "pagar", "sexto", "pluma", "sabia", 
    "bruxa", "xampu", "repor", "fatuo", "corar",
]

    print(len(palavras))

    with sqlite3.connect(DATABASE) as conn:
        cursor = conn.cursor()
        cursor.execute('''
            CREATE TABLE IF NOT EXISTS palavras (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                palavra TEXT NOT NULL
            )
        ''')
        cursor.executemany('INSERT INTO palavras (palavra) VALUES (?)', [(palavra,) for palavra in palavras])

if __name__ == '__main__':
    create_db()




